#!/bin/bash

aa=`ps -aux | grep -v grep | grep arubasyslog | awk '{print $2}' | wc -l`

if [ "$aa" -ne 1 ]; then
	cd /arubasyslog
	killall -9 arubasyslog
	nohup ./arubasyslog &
	head -1 arubasyslog.c | awk '{printf "%s ",$2}' >> mylog
	date >> mylog
fi
